# Generated by Django 4.1.4 on 2023-01-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, unique=True)),
                ("title", models.CharField(max_length=400)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("image", models.ImageField(blank=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark_shose", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_dom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=40)),
                ("color", models.CharField(blank=True, max_length=40)),
                ("brand", models.CharField(blank=True, max_length=40)),
                (
                    "dom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amir_app.dom"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100, unique=True)),
                ("brand_shose", models.CharField(blank=True, max_length=200)),
                ("size_shose", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("mark", models.ManyToManyField(blank=True, to="amir_app.mark")),
                ("tag", models.ManyToManyField(blank=True, to="amir_app.tag")),
            ],
        ),
        migrations.AddField(
            model_name="dom",
            name="tag",
            field=models.ManyToManyField(blank=True, to="amir_app.tag"),
        ),
    ]
